name: Pull Request
run-name: 'Pull Request 🚧 ${{ github.event.pull_request.title }}'

on:
  pull_request:

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        framework: [net8.0, net9.0]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --framework ${{ matrix.framework }}
    - name: Test
      run: dotnet test --no-build --verbosity normal --framework ${{ matrix.framework }}
