name: Release Packages
run-name: 'Release Packages 📦 ${{ github.ref_name }}'

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Extract Version from Tag
      run: |
        TAG_VERSION="${GITHUB_REF#refs/tags/}"
        echo "VERSION=$TAG_VERSION" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${{ env.VERSION }}
    - name: Pack
      run: dotnet pack --no-build --configuration Release --output ./artifacts /p:Version=${{ env.VERSION }}
